[review]
allow-users = [
  "ywqzzy",
  "xzhangxian1008",
  "Qiaolin-Yu",
  "yibin87",
  "zanmato1984",
  "guo-shaoge",
  "bestwoody",
  "SeaRise",
  "XuHuaiyu",
  "wshwsh12",
  "windtalker",
  "mengxin9014",
  "solotzg",
  "gengliqi",
  "LittleFall",
]
block-comments = [
  "/run-",
  "/merge",
  "/rebuild",
]
block-labels = [
  "cherry-pick-approved",
  "status/can-merge",
]
block-users = [
  "sre-bot",
  "ti-chi-bot",
  "ti-srebot",
  "codecov",
  "codecov[bot]",
  "codecov-commenter",
  "CLAassistant",
  "hound[bot]",
]
lgtm-comments = [
  "/lgtm",
  "LGTM",
]

# Could also be set with the environment variable:
#   - GHSTATS_GITHUB_TOKEN
#   - GHSTATS_FEISHU_WEBHOOK_TOKEN
[review.access]
feishu-webhook-token = ""
github-token = ""

[[review.repos]]
name = "Compute A&E"
pr-query = [
  """
repo:tikv/pd
""",
  """
repo:tikv/client-go
""",
  """
repo:tikv/tikv
""",
  """
repo:pingcap/tidb
""",
  """
repo:pingcap/kvproto
""",
  """
repo:pingcap/tiflash
""",
  """
repo:pingcap/test-plan
""",
  """
repo:pingcap/endless
""",
  """
repo:pingcap/tipb
""",
  """
repo:pingcap/tiflash-scripts
""",
]
